//go:build android_ndk35

// Code generated by capigen. DO NOT EDIT.

package camera

/*
#cgo LDFLAGS: -lcamera2ndk
#undef __ANDROID_MIN_SDK_VERSION__
#define __ANDROID_MIN_SDK_VERSION__ 35
#define __ANDROID_UNAVAILABLE_SYMBOLS_ARE_WEAK__ 1
#include "camera/NdkCameraManager.h"
#include "camera/NdkCameraDevice.h"
#include "camera/NdkCaptureRequest.h"
#include "camera/NdkCameraCaptureSession.h"
#include "camera/NdkCameraMetadata.h"
#include "camera/NdkCameraMetadataTags.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

var _ runtime.Error
var _ unsafe.Pointer

func ACameraMetadata_getTagFromName(metadata *ACameraMetadata, name string, tag *uint32) Camera_status_t {
	cmetadata, cmetadataAllocMap := (*C.ACameraMetadata)(unsafe.Pointer(metadata)), cgoAllocsUnknown
	cname, cnameAllocMap := UnpackPCharString(name)
	ctag, ctagAllocMap := (*C.uint)(unsafe.Pointer(tag)), cgoAllocsUnknown
	__ret := C.ACameraMetadata_getTagFromName(cmetadata, cname, ctag)
	runtime.KeepAlive(ctagAllocMap)
	runtime.KeepAlive(cnameAllocMap)
	runtime.KeepAlive(cmetadataAllocMap)
	__v := (Camera_status_t)(__ret)
	return __v
}
