// Code generated by capigen. DO NOT EDIT.

#include "_cgo_export.h"

char* APersistableBundle_stringAllocator_d22e9a69(int32_t sizeBytes, void* context) {
	return APersistableBundle_stringAllocatorD22E9A69(sizeBytes, context);
}
