// Code generated by capigen. DO NOT EDIT.

#include "android/persistable_bundle.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// APersistableBundle_stringAllocator_d22e9a69 is a proxy for callback APersistableBundle_stringAllocator.
char* APersistableBundle_stringAllocator_d22e9a69(int32_t sizeBytes, void* context);
