// Code generated by capigen. DO NOT EDIT.

#include "_cgo_export.h"

void AStorageManager_obbCallbackFunc_a6785822(const char* filename, const int32_t state, void* data) {
	AStorageManager_obbCallbackFuncA6785822((char*)filename, state, data);
}

